# Generated by Django 3.2.5 on 2022-05-06 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dcim', '0131_consoleport_speed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SID',
            fields=[
                ('created', models.DateField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sid', models.PositiveIntegerField(unique=True)),
                ('device', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sids', to='dcim.device')),
            ],
            options={
                'verbose_name': 'SID',
                'verbose_name_plural': 'SIDs',
            },
        ),
    ]
